/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * A live Rust runtime handed to the platform bridge.
 *
 * The platform never sees provider wire formats or tool internals, only
 * domain summaries and normalized turn events.
 */
export declare class SujiuRuntimeBridge {
  /**
   * Attaches a directory the runtime may persist to.
   *
   * The platform chooses the location; the runtime decides what goes in it.
   * Attaching after startup restores a document that is already there, so a
   * frontend can hand the directory over whenever it learns it.
   */
  useDataDirectory(directory: string): void
  /** The directory currently attached, or null when the runtime is in memory. */
  dataDirectory(): string | null
  /** The shared runtime version, so a platform can report what it is bound to. */
  coreVersion(): string
  listSessions(): Array<SessionSummaryDto>
  listCharacters(query?: string | undefined | null): Array<CharacterSummaryDto>
  listModels(): Array<ModelSummaryDto>
  /**
   * Ask the endpoint which models it serves.
   *
   * A convenience for the settings screen. It never decides how a turn
   * runs, and `manualEntryAllowed` is always true: a gateway with no model
   * list still chats, so a listing failure must not take the manual choice
   * away.
   */
  discoverModels(apiKey?: string | undefined | null): ModelDiscoveryDto
  listContextSources(): Array<ContextSourceDto>
  conversationState(sessionId: string): ConversationSnapshotDto
  createSession(characterId: string): string
  /**
   * Open a conversation with any number of characters.
   *
   * This is the form that needs no fiction about a main character: an empty
   * list is a conversation with nobody in it yet, one is the ordinary chat,
   * and several is a table. The single-character path above is a shortcut
   * into this one, not a different storage model.
   */
  createConversation(participants: Array<ParticipantRequestDto>, personaId?: string | undefined | null, worldbookIds?: Array<string> | undefined | null, promptProfileId?: string | undefined | null): string
  /**
   * Every stored persona, as list rows.
   *
   * Its own call rather than a column on `list_characters`: a persona is a
   * separate entity, and keeping it inside a character's shape is exactly what
   * made it invisible.
   */
  listPersonas(): Array<PersonaDto>
  /**
   * One persona in full, for an editor.
   *
   * A different shape from the list row on purpose: an editor needs the
   * bodies, and a summary would leave it nothing to prefill and nothing to
   * tell "empty" from "unchanged".
   */
  persona(id: string): PersonaRequestDto | null
  savePersona(persona: PersonaRequestDto): string
  deletePersona(id: string): boolean
  /**
   * Every stored world book, each with its entries.
   *
   * Entries travel with the book because an entry has no meaning outside the
   * book holding it: an editor has to have the whole book to save one entry.
   */
  listWorldBooks(): Array<WorldBookDto>
  saveWorldBook(book: WorldBookRequestDto): string
  deleteWorldBook(id: string): boolean
  /**
   * Every stored prompt profile, as list rows.
   *
   * The domain calls it a prompt profile because that is what it is; a screen
   * may show it as "Prompts" and say nothing about the type name.
   */
  listPromptProfiles(): Array<PromptProfileDto>
  /** One prompt profile in full, for an editor. */
  promptProfile(id: string): PromptProfileRequestDto | null
  savePromptProfile(profile: PromptProfileRequestDto): string
  deletePromptProfile(id: string): boolean
  /**
   * Create or edit a character.
   *
   * Exposed because a library has to be editable, not only readable: a user
   * who cannot correct a character's own words has to delete and recreate it,
   * which loses every conversation that bound it.
   */
  saveCharacter(character: CharacterRequestDto): string
  /**
   * One character in full, for an editor to prefill from.
   *
   * `list_characters` answers with summaries, and a summary has no scenario,
   * no first message and no prompt bodies. An editor prefilled from one starts
   * blank over a character that is fully written, and saving it would replace
   * everything with what survived in three fields.
   *
   * Resolves to nothing for a blank or unknown id, which is the answer a
   * "new character" form wants.
   */
  character(id: string): CharacterRequestDto | null
  deleteCharacter(id: string): boolean
  /**
   * Replace what a conversation binds.
   *
   * This is the conversation half of the split: it changes which stored
   * resources one chat *uses* and never edits those resources, so a persona
   * bound in two conversations stays one persona. The transcript is left
   * alone — changing who is in a room is not rewriting what has already been
   * said in it.
   */
  setConversationBindings(sessionId: string, participants: Array<ParticipantRequestDto>, personaId?: string | undefined | null, worldbookIds?: Array<string> | undefined | null, promptProfileId?: string | undefined | null): void
  /**
   * The wire formats the runtime speaks, in the order it tries them.
   *
   * This replaces the list of provider kinds a settings screen used to be
   * given. A vendor list asked the user to decide something negotiation
   * settles by asking the endpoint, and a name in that list could be wrong
   * for the very address the user typed.
   */
  supportedProtocols(): Array<string>
  /**
   * Store the endpoint a settings screen configured.
   *
   * There is no kind to reject: an address the runtime has never heard of
   * is exactly the self-hosted gateway this is meant to support. Whether it
   * can be reached, and what it speaks, is what the first turn's
   * negotiation answers.
   */
  configureProvider(provider: ProviderConfigDto): void
  /**
   * Read back what is already configured, so a settings form can open on
   * the truth rather than on three empty fields.
   *
   * No credential comes back. The key lives in platform storage and is
   * never something a form can read into a field and then leak into a log
   * line or a state dump.
   */
  storedEndpoint(): StoredEndpointDto | null
  /**
   * What an endpoint told us before, without asking it again.
   *
   * This is what a platform reads at launch so the model list is already
   * there. It never reaches the network, which is the difference from
   * `discover_endpoint`: a launch that quietly asked would cost every user a
   * round trip every time they opened the app, and on a free tier a rate
   * limit as well.
   */
  rememberedEndpoint(baseUrl: string): EndpointExplorationDto | null
  /**
   * Find out what an endpoint is, from an address and a key and nothing else.
   *
   * This is the order the user actually works in, and it is why the settings
   * screen can be shown a model list before anything has been saved: there is
   * no configuration to complete first, and no model to know in advance.
   * The model list and the protocol are reported as two independent answers,
   * because a gateway can list nothing and still speak Responses.
   *
   * `refresh` is what a platform's "ask again" button passes. Leaving it out
   * asks the cache, which is what an ordinary open of a settings screen
   * wants: the endpoint already answered this, and re-asking costs the user a
   * wait and the endpoint a rate limit.
   */
  discoverEndpoint(baseUrl: string, apiKey: string, refresh?: boolean | undefined | null): EndpointExplorationDto
  /** Sends one turn. The callback receives normalized turn events as JSON. */
  sendTurn(request: TurnRequestDto, onEvent: ((err: Error | null, arg: string) => any)): Promise<unknown>
  cancelTurn(): void
  /**
   * The diagnostic log, oldest entry first.
   *
   * This is what makes a failure debuggable instead of guessable: it names the
   * endpoint, every protocol that was tried, what each one answered, whether
   * the model list worked, which protocol and model the turn actually used,
   * and which stage a failure happened in. `limit` is a number of most
   * recent entries; zero means everything the log still holds.
   */
  diagnostics(limit?: number | undefined | null): Array<DiagnosticEntryDto>
  /**
   * Only the capability and model probing half of the log.
   *
   * Someone deciding which key to type wants the endpoint's behaviour, not
   * the last conversation's traffic.
   */
  discoveryDiagnostics(limit?: number | undefined | null): Array<DiagnosticEntryDto>
  /** The whole log as text, for the "copy this into a bug report" case. */
  diagnosticsText(): string
  /**
   * Start a fresh investigation. The stored endpoint and key are untouched:
   * the log is evidence, not configuration.
   */
  clearDiagnostics(): void
}

/** A character to store. Same id rule as [`PersonaRequestDto`]. */
export interface CharacterRequestDto {
  id?: string
  name: string
  description: string
  personality: string
  scenario: string
  firstMessage: string
  alternateGreetings: Array<string>
  exampleDialogue: string
  systemPrompt: string
  postHistoryInstructions: string
  worldbookIds: Array<string>
}

export interface CharacterSummaryDto {
  id: string
  name: string
  description: string
}

export interface ContextSourceDto {
  id: string
  kind: string
  name: string
  description: string
  recordCount: number
}

export interface ConversationSnapshotDto {
  sessionId: string
  /** The first participant, for a screen that still shows one character. */
  character?: CharacterSummaryDto
  participants: Array<ParticipantDto>
  personaId?: string
  worldbookIds: Array<string>
  promptProfileId?: string
  messages: Array<MessageDto>
}

export declare function coreVersion(): string

/**
 * Builds a runtime from the seed catalog that ships with the app.
 *
 * This is a free function rather than an associated one on purpose: a factory
 * declared inside `impl SujiuRuntimeBridge` is registered as a static method
 * on the exported class, so ArkTS would have to call
 * `SujiuRuntimeBridge.create()` instead of `create()`.
 */
export declare function create(): SujiuRuntimeBridge

/**
 * One line of the diagnostic log, as a settings screen or a bug report needs it.
 *
 * The text arrived already redacted. Nothing here is a raw body, and nothing
 * here is a credential: the runtime removes those before a line is ever
 * recorded, so a platform can render or share this without a second pass.
 */
export interface DiagnosticEntryDto {
  /**
   * `discovery` for capability and model probing, `chat` for a conversation.
   * The two are separate investigations and a reader must be able to tell
   * which one a line belongs to.
   */
  kind: string
  /**
   * Where in that investigation this line sits: `probe_start`,
   * `protocol_result`, `chat_request`, `turn_failed`, and so on.
   */
  stage: string
  message: string
  atMs: number
  /** The detail as a rendered `key=value` line, ready to show. */
  detail: string
}

/**
 * What an unsaved endpoint turned out to be.
 *
 * `protocol` and `models` are two independent answers, and reporting them as
 * one would be a claim Sujiu cannot make: an endpoint that lists nothing may
 * still speak the newest protocol, and one that lists fifty models may speak
 * only the oldest.
 */
export interface EndpointExplorationDto {
  protocol: string
  protocols: Array<string>
  /**
   * How the protocol probe came out, as a code to branch on.
   *
   * A settings screen shows a different message per code. "Probe failed" as a
   * single message is the state this replaces: a wrong key, a wrong path and
   * a switched-off router all read the same, and each of them sends the user
   * to edit a different field.
   */
  status: string
  /**
   * Why no protocol was settled, when none was. A sentence to read; `status`
   * is what to switch on.
   */
  reason?: string
  models: ModelDiscoveryDto
}

export interface MessageDto {
  id: string
  role: string
  /**
   * Which participant spoke, when the transcript says.
   *
   * A conversation can hold several characters, so `role: "assistant"` alone
   * does not say who is talking. Undefined means the step carries no
   * attribution: choosing who speaks next is a speaking-order policy, and the
   * runtime does not invent one.
   */
  speakerId?: string
  text: string
  toolCalls: Array<ToolCallDto>
}

/** What model discovery found, and what the user may still do about it. */
export interface ModelDiscoveryDto {
  listing: string
  note: string
  /** Always true, so a settings screen can keep the manual field enabled. */
  manualEntryAllowed: boolean
  models: Array<ModelSummaryDto>
}

export interface ModelSummaryDto {
  id: string
  name: string
  endpointId: string
  /**
   * A word to show a person, derived from the address. It names who answers
   * and decides nothing: a gateway behind the same name can serve unrelated
   * models, and the runtime never asks it.
   */
  endpointLabel: string
  configured: boolean
}

/**
 * One character taking part in a conversation.
 *
 * A conversation is the root of a chat, and it may hold no participant, one
 * character, or a whole table of them. Nothing here implies a "main"
 * character; a table top is a game master plus several others.
 */
export interface ParticipantDto {
  characterId: string
  name: string
  /** `character` or `narrator`, as a label a screen may show. */
  role: string
}

/**
 * What a screen is asked to open a conversation with.
 *
 * A bare character id still creates a one-participant conversation, so an
 * existing platform flow keeps working while the model underneath is already
 * group-shaped.
 */
export interface ParticipantRequestDto {
  characterId: string
  role?: string
  displayName?: string
}

/**
 * One stored persona, as a list row.
 *
 * A persona is an entity a user owns, not a field of a character card, which is
 * why it has its own list here. Nothing in this shape implies that anything is
 * bound to anything: which persona a chat uses is that conversation's answer,
 * and it is asked separately.
 */
export interface PersonaDto {
  id: string
  name: string
  description: string
  /** How many world books this persona brings of its own. */
  worldbookCount: number
}

/**
 * A persona to store.
 *
 * `id` is absent or blank to create one. A present id that names nothing is
 * refused rather than treated as a create: a screen that lost the persona it was
 * editing would otherwise be told it saved, and would have saved a duplicate
 * under the same name.
 */
export interface PersonaRequestDto {
  id?: string
  name: string
  description: string
  userPrompt: string
  worldbookIds: Array<string>
}

/**
 * One prompt profile, as a list row.
 *
 * Only the name. The four prompt bodies are what the profile *says*, and a row
 * carrying all of them would be a wall of text rather than a row.
 */
export interface PromptProfileDto {
  id: string
  name: string
}

/**
 * A prompt profile to store. Same id rule as [`PersonaRequestDto`].
 *
 * The named fields are the whole of what a basic editor can change, and the
 * runtime keeps the profile's fixed segments when this is saved.
 */
export interface PromptProfileRequestDto {
  id?: string
  name: string
  systemPrompt: string
  userPrompt: string
  postHistoryInstructions: string
  formatRules: string
}

export interface ProviderConfigDto {
  id: string
  name: string
  baseUrl: string
  /**
   * The model the user picked, if they have picked one yet.
   *
   * Optional because exploration runs first: an endpoint is worth asking
   * about before anyone has chosen what to ask it. A form that insists on
   * a model before it will save is the reason discovery used to have to
   * come last.
   */
  selectedModel?: string
  maxTokens?: number
  temperature?: number
  /**
   * Whether this endpoint needs the assistant reasoning that produced a tool
   * call sent back with it.
   *
   * Optional because most endpoints do not, and a known thinking-mode
   * service is recognised without it. A platform only describes the provider
   * it was given; the protocol requirement is the runtime's answer, so this
   * is a stated capability rather than something a form has to know about.
   */
  replaysAssistantReasoning?: boolean
}

export interface SessionSummaryDto {
  id: string
  /**
   * The first participant, for a screen that still shows one character.
   * Read [`Self::participants`] for the conversation as it really is.
   */
  characterId: string
  /** The first participant's name, for the same reason. */
  characterName: string
  participants: Array<ParticipantDto>
  preview: string
  title: string
  updatedAtMs: number
  messageCount: number
}

/**
 * An endpoint that is already stored, as far as a form may know one.
 *
 * No credential field, and none is wanted: a form that could read the key back
 * would be one `dump the view state` away from writing it to a log. The key is
 * the one thing a settings screen asks to be told "yes you have one" and
 * nothing more.
 */
export interface StoredEndpointDto {
  id: string
  baseUrl: string
  /**
   * `None` until the user has chosen one, which is a normal state: an
   * endpoint can be asked what it offers before anyone picks a model.
   */
  selectedModel?: string
  /** A word to show a person. Decides nothing. */
  label: string
}

export interface ToolCallDto {
  id: string
  name: string
  title: string
  status: string
  isError: boolean
  resultText: string
}

export interface TurnRequestDto {
  sessionId: string
  userText: string
  provider?: ProviderConfigDto
  apiKey?: string
}

/** One world book, with its entries. */
export interface WorldBookDto {
  id: string
  name: string
  entries: Array<WorldBookEntryDto>
}

/** One world-book entry, as an editor sees it. */
export interface WorldBookEntryDto {
  id: string
  name: string
  /**
   * The entry's text, unshortened.
   *
   * This is lore the model reads, so a preview here would be a truncation
   * rule baked into the bridge, and choosing what counts as the interesting
   * sentence of a piece of lore is not this layer's decision to make.
   */
  content: string
  keys: Array<string>
  enabled: boolean
  constant: boolean
  /** `before_character`, `after_character` or `near_history`. */
  position: string
}

/** A world-book entry to store. */
export interface WorldBookEntryRequestDto {
  id?: string
  name: string
  content: string
  keys: Array<string>
  /**
   * Absent means the runtime's default, which is enabled: an entry the user
   * just wrote and cannot see is worse than one that works.
   */
  enabled?: boolean
  constant?: boolean
  position?: string
}

/** A world book to store. Same id rule as [`PersonaRequestDto`]. */
export interface WorldBookRequestDto {
  id?: string
  name: string
  entries: Array<WorldBookEntryRequestDto>
}
